# my global config
global:
  scrape_interval: 1s
  evaluation_interval: 1s
  external_labels:
    monitor: "Emso-Container"

rule_files:
  - "./rules/servertest/container-demo.yml"

# alert
alerting:
  alertmanagers:
    - scheme: http
      static_configs:
        - targets: ["10.0.0.232:9093"]
      # basic_auth:
      #   username: admin
      #   password: vietnam@1234

scrape_configs:
  - job_name: "yugabytedb"
    metrics_path: /prometheus-metrics
    relabel_configs:
      - target_label: "node_prefix"
        replacement: "cluster-1"
    metric_relabel_configs:
      # Save the name of the metric so we can group_by since we cannot by __name__ directly...
      - source_labels: ["__name__"]
        regex: "(.*)"
        target_label: "saved_name"
        replacement: "$1"
      # The following basically retrofit the handler_latency_* metrics to label format.
      - source_labels: ["__name__"]
        regex: "handler_latency_(yb_[^_]*)_([^_]*)_([^_]*)(.*)"
        target_label: "server_type"
        replacement: "$1"
      - source_labels: ["__name__"]
        regex: "handler_latency_(yb_[^_]*)_([^_]*)_([^_]*)(.*)"
        target_label: "service_type"
        replacement: "$2"
      - source_labels: ["__name__"]
        regex: "handler_latency_(yb_[^_]*)_([^_]*)_([^_]*)(_sum|_count)?"
        target_label: "service_method"
        replacement: "$3"
      - source_labels: ["__name__"]
        regex: "handler_latency_(yb_[^_]*)_([^_]*)_([^_]*)(_sum|_count)?"
        target_label: "__name__"
        replacement: "rpc_latency$4"
    static_configs:
      - targets:
          [
            "172.16.0.98:7000",
          ]
        labels:
          export_type: "master_export"
      - targets:
          [
            "172.16.0.98:9000",
          ]
        labels:
          export_type: "tserver_export"
      - targets:
          [
            "172.16.0.98:12000",
          ]
        labels:
          export_type: "cql_export"
      - targets:
          [
            "172.16.0.98:13000",
          ]
        labels:
          export_type: "ysql_export"
