# my global config
global:
  scrape_interval:     1s 
  evaluation_interval: 1s 

  external_labels:
    monitor: 'Hospitals-Container'

rule_files:
  - './rules/servertest/Isofh/10.0.0.20/jiraserver.yml'

# alert
alerting:
  alertmanagers:
  - scheme: http
    static_configs:
    - targets: ['10.0.0.232:9093']
    # basic_auth:
    #   username: admin
    #   password: vietnam@1234

scrape_configs:
  - job_name: 'isofh-local'
    scrape_interval: 5s
    static_configs:
      - targets: 
        - '10.0.0.55:11092'
        - '10.0.0.55:8080'
        - '10.0.0.20:19093'
        - '10.0.0.20:19092'
        - '10.0.0.10:9101'
        - '10.0.0.232:19100'
        - '10.0.0.55:7000'
  - job_name: 'loki'
    scrape_interval: 5s
    static_configs:
      - targets: 
        - '10.0.0.232:3100'