groups:
  - name: ysql-cache-monitoring
    rules:
      # ALERT RULES CHO master_export
      - alert: (YSQL-MASTER)-ExporterDown
        expr: pg_up{job="[YugabyteDB-Service-Prod]-Metrics service -- dịch vụ", export_type="master_export"} == 0
        for: 1m
        labels:
          severity: critical
        annotations:
          summary: "Exporter trên master không phản hồi"
          description: "pg_up == 0 trên node master_export. Kiểm tra exporter hoặc dịch vụ."

      - alert: (YSQL-MASTER)-ScrapeError
        expr: pg_exporter_last_scrape_error{job="[YugabyteDB-Service-Prod]-Metrics service -- dịch vụ", export_type="master_export"} == 1
        for: 30s
        labels:
          severity: warning
        annotations:
          summary: "Lỗi scrape trên master_export"
          description: "Prometheus gặp lỗi khi scrape dữ liệu exporter từ master_export."

      - alert: (YSQL-MASTER)-ScrapeDurationHigh
        expr: pg_exporter_last_scrape_duration_seconds{job="[YugabyteDB-Service-Prod]-Metrics service -- dịch vụ", export_type="master_export"} > 2
        for: 1m
        labels:
          severity: warning
        annotations:
          summary: "Thời gian scrape cao trên master"
          description: "Scrape exporter mất hơn 2 giây. Có thể hệ thống đang quá tải hoặc có vấn đề mạng."

      # ALERT RULES CHO tserver_export
      - alert: (YSQL-TSERVER)-ExporterDown
        expr: pg_up{job="[YugabyteDB-Service-Prod]-Metrics service -- dịch vụ", export_type="tserver_export"} == 0
        for: 1m
        labels:
          severity: critical
        annotations:
          summary: "Exporter trên tserver không phản hồi"
          description: "pg_up == 0 trên node tserver_export. Kiểm tra exporter hoặc container."

      - alert: (YSQL-TSERVER)-ScrapeError
        expr: pg_exporter_last_scrape_error{job="[YugabyteDB-Service-Prod]-Metrics service -- dịch vụ", export_type="tserver_export"} == 1
        for: 30s
        labels:
          severity: warning
        annotations:
          summary: "Lỗi scrape trên tserver_export"
          description: "Prometheus gặp lỗi khi scrape dữ liệu exporter từ tserver_export."

      - alert: (YSQL-TSERVER)-ScrapeDurationHigh
        expr: pg_exporter_last_scrape_duration_seconds{job="[YugabyteDB-Service-Prod]-Metrics service -- dịch vụ", export_type="tserver_export"} > 2
        for: 1m
        labels:
          severity: warning
        annotations:
          summary: "Thời gian scrape cao trên tserver"
          description: "Scrape exporter mất hơn 2 giây. Có thể hệ thống đang quá tải hoặc có vấn đề mạng."

      - alert: (YSQL-TSERVER)-CacheHitRateLow
        expr: rate(pg_response_cache_hits{job="[YugabyteDB-Service-Prod]-Metrics service -- dịch vụ", export_type="tserver_export"}[5m])
              / rate(pg_response_cache_queries{job="[YugabyteDB-Service-Prod]-Metrics service -- dịch vụ", export_type="tserver_export"}[5m]) < 0.3
        for: 3m
        labels:
          severity: warning
        annotations:
          summary: "Tỷ lệ hit cache thấp trên TServer"
          description: "Tỷ lệ cache hit dưới 30% trong 5 phút. Có thể ảnh hưởng hiệu năng đọc."

      - alert: (YSQL-TSERVER)-CacheEntriesHigh
        expr: pg_response_cache_entries{job="[YugabyteDB-Service-Prod]-Metrics service -- dịch vụ", export_type="tserver_export"} > 10000
        for: 5m
        labels:
          severity: info
        annotations:
          summary: "Số lượng entries cache cao trên TServer"
          description: "Số lượng bản ghi trong cache vượt 10,000. Cần xem xét cleanup."

      - alert: (YSQL-TSERVER)-CacheGCSpike
        expr: increase(pg_response_cache_gc_calls{job="[YugabyteDB-Service-Prod]-Metrics service -- dịch vụ", export_type="tserver_export"}[5m]) > 50
        for: 1m
        labels:
          severity: warning
        annotations:
          summary: "Số lần gọi GC cache tăng trên TServer"
          description: "Garbage collection cache xảy ra quá nhiều lần trong thời gian ngắn."

      - alert: (YSQL-TSERVER)-CacheDisableSpike
        expr: increase(pg_response_cache_disable_calls{job="[YugabyteDB-Service-Prod]-Metrics service -- dịch vụ", export_type="tserver_export"}[5m]) > 5
        for: 1m
        labels:
          severity: info
        annotations:
          summary: "Cache bị disable đột biến trên TServer"
          description: "Có nhiều lần gọi vô hiệu hóa cache. Cần kiểm tra ứng dụng hoặc config."

      - alert: (YSQL-TSERVER)-ResponseCacheQuerySpike
        expr: increase(pg_response_cache_queries{job="[YugabyteDB-Service-Prod]-Metrics service -- dịch vụ", export_type="tserver_export"}[5m]) > 1000
        for: 1m
        labels:
          severity: info
        annotations:
          summary: "Truy vấn cache tăng đột biến"
          description: "Truy vấn thông qua cache tăng nhanh, có thể do truy cập lớn hoặc batch xử lý."
