global:
  resolve_timeout: 30s

receivers:
- name: tuan-telegram
  webhook_configs:
  - url: 'http://172.16.0.225:32802/alert/-4659848306'

# - name: System-Team
#   telegram_configs:
#   - api_url: https://api.telegram.org
#     bot_token: 6623410843:AAFXWQcnUEqQviOLo_YtxKqNoM5xw8Snoic
#     chat_id: -999710731
#     # template: /etc/alertmanager/template/template.tmpl
#     disable_notifications: false
#     http_config:
#       follow_redirects: true
#     send_resolved: true
#     parse_mode: 'HTML'



route:
  continue: false
  group_by: ['instance','job','category','container_name','app','hostname','alertname']
  group_interval: 30s
  group_wait: 10s
  repeat_interval: 1m
  receiver: System-Team
  routes:
    - match:
        job: mongo-exporter
      receiver: tuan-telegram
      group_wait: 2s















templates:
- '/etc/alertmanager/template/template.tmpl'




# docker run -p 9101:9101 quay.io/prometheus/haproxy-exporter:latest --haproxy.scrape-uri="http://admin:1@10.0.0.10:9000/haproxy?stats;csv"