global:
  resolve_timeout: 30s

receivers:
- name: tuan-telegram
  webhook_configs:
  - url: 'http://172.16.0.225:32802/alert/-4779449673'

- name: k8s-telegram
  webhook_configs:
  - url: 'http://172.16.0.225:32803/alert/-4972407237'

- name: database-telegram
  webhook_configs:
  - url: 'http://172.16.0.225:32804/alert/-4828054469'


- name: null-receiver
  webhook_configs: []   # không gửi đi đâu cả



route:
  continue: false
  group_by: ['instance','job','category','container_name','app','hostname','alertname','export_type','namespace','pod','uid','reason','service','cluster_name','severity','node','app_kubernetes_io_version','app_type']
  group_wait: 30s
  group_interval: 5m
  repeat_interval: 1h
  receiver: null-receiver
  routes:
    - match:
        job: node-exporter
      receiver: tuan-telegram
      group_wait: 30s
      group_interval: 5m
      repeat_interval: 1h
      
    - match_re:
        job: "kubernetes-pods|kubernetes-pods-slow|kubernetes-nodes|kubernetes-service-endpoints|kubernetes-apiservers|kubernetes-nodes-cadvisor|prometheus"
      receiver: k8s-telegram
      group_wait: 30s
      group_interval: 5m
      repeat_interval: 1h

    - match_re:
        job: "[YugabyteDB-Service-Prod]-Metrics service -- dịch vụ|[Redis-Cluster-Prod]-Metrics service -- dịch vụ|[Redis-Server-Prod]-Metrics service -- dịch vụ|[Gorse-Service-DB-Prod]-Metrics service REDIS -- dịch vụ|[Elasticsearch-Service-DB-Prod]-Metrics service ELASTICSEARCH -- dịch vụ|[Chat-Service-DB-Prod]-Metrics service MONGODB -- dịch vụ|[Kafka-Service-Prod]-Metrics service -- dịch vụ|[Notification-Service-DB-Prod]-Metrics service MONGODB -- dịch vụ |[Pt-Service-DB-Prod]-Metrics service POSTGRES -- dịch vụ|"
      receiver: database-telegram
      group_wait: 30s
      group_interval: 5m
      repeat_interval: 1h












templates:
- '/etc/alertmanager/template/template.tmpl'

