global:
  resolve_timeout: 30s

receivers:
- name: tuan-telegram
  webhook_configs:
  - url: 'http://172.16.0.225:32802/alert/-7658537112'

# - name: System-Team
#   telegram_configs:
#   - api_url: https://api.telegram.org
#     bot_token: 6623410843:AAFXWQcnUEqQviOLo_YtxKqNoM5xw8Snoic
#     chat_id: -999710731
#     # template: /etc/alertmanager/template/template.tmpl
#     disable_notifications: false
#     http_config:
#       follow_redirects: true
#     send_resolved: true
#     parse_mode: 'HTML'



route:
  continue: false
  group_by: ['instance','job','category','container_name','app','hostname','alertname','export_type','env']
  group_wait: 30s
  group_interval: 5m
  repeat_interval: 3h
  receiver: tuan-telegram
  routes:
    - match:
        job: node-exporter
      receiver: tuan-telegram
      group_wait: 30s
      group_interval: 5m
      repeat_interval: 3h















templates:
- '/etc/alertmanager/template/template.tmpl'

