groups:
- name: server-status
  rules:
  - alert: STATUS SERVER
    expr: up == 0
    for: 2m
    labels:
      severity: critical
    annotations:
      summary: "Máy chủ {{ $labels.instance }} bị tắt"
      description: "Hệ thống phát hiện máy chủ {{ $labels.instance }} đã ngừng phản hồi trong hơn 2 phút. Vui lòng kiểm tra tình trạng kết nối hoặc dịch vụ."

  - alert: CPU SERVER
    expr: 100 - avg by (instance,job,hostname,env,instance) (irate(node_cpu_seconds_total{mode="idle"}[2m])) * 100 > 95
    for: 2m
    labels:
      severity: warning
    annotations:
      summary: "Máy chủ {{ $labels.instance }} sử dụng CPU cao trong 5 phút"
      description: | 
          "Mức sử dụng CPU của máy chủ {{ $labels.instance }} 
          đã vượt quá 95% trong 5 phút. Giá trị hiện tại: {{ printf "%.2f" $value }}% "

  - alert: RAM SERVER
    expr: (node_memory_MemTotal_bytes - (node_memory_MemFree_bytes + node_memory_Cached_bytes + node_memory_Buffers_bytes)) / node_memory_MemTotal_bytes * 100 > 95
    for: 2m
    labels:
      severity: warning
    annotations:
      summary: "Máy chủ {{ $labels.instance }} sử dụng RAM cao trong 5 phút"
      description: |
           "Mức sử dụng RAM của máy chủ {{ $labels.instance }} 
            đã vượt quá 95% trong 5 phút. Giá trị hiện tại: {{ printf "%.2f" $value }}% "

  - alert: DISK SERVER
    expr: 100 - (node_filesystem_avail_bytes{mountpoint!~"/run/.*",fstype!~"tmpfs|overlay"}) / node_filesystem_size_bytes{mountpoint!~"/run/.*",fstype!~"tmpfs|overlay"} * 100 > 95
    for: 5m
    labels:
      severity: warning
    annotations:
      summary: "Máy chủ {{ $labels.instance }} sử dụng dung lượng đĩa cao tại {{ $labels.mountpoint }}"
      description: |
           "Ổ đĩa {{ $labels.mountpoint }} 
            trên máy chủ {{ $labels.instance }} 
            đã sử dụng trên 95% dung lượng trong 5 phút. Mức sử dụng hiện tại: {{ printf "%.2f" $value }}%"

  - alert: HIGH NETWORK SERVER 
    expr: rate(node_network_receive_bytes_total{device=~"ens.*|eth.*|enp.*|eno.*"}[5m]) / 1024 / 1024 > 50
    for: 5m
    labels:
      severity: warning
    annotations:
      summary: "Máy chủ {{ $labels.instance }} có lưu lượng nhận mạng cao trên thiết bị {{ $labels.device }}"
      description: |
           "Lưu lượng nhận mạng trên thiết bị {{ $labels.device }} 
            của máy chủ {{ $labels.instance }} 
            đã vượt quá 50MB/s trong 5 phút. Giá trị hiện tại: {{ $value }} MB/s."


