groups:
  - name: server-yugabyte
    rules:
      - alert: Yugabyte_Active
        expr: up{job="[YugabyteDB-Service-Prod]-Metrics-service"} == 0
        for: 2m
        labels:
          severity: critical
        annotations:
          summary: "Node {{ $labels.instance }} không phản hồi"
          description: "Node {{ $labels.instance }} đã không phản hồi trong 2 phút. Kiểm tra kết nối hoặc trạng thái dịch vụ."

      - alert: Yugabyte_TimeError
        expr: hybrid_clock_error{job="[YugabyteDB-Service-Prod]-Metrics-service"} > 500000
        for: 2m
        labels:
          severity: critical
        annotations:
          summary: "Sai số ước lượng đồng hồ tại {{ $labels.instance }}"
          description: |
            ▸ Giá trị hiện tại: {{ $value }} microseconds

      - alert: Yugabyte_ClockSkew_Master
        expr: hybrid_clock_skew{job="[YugabyteDB-Service-Prod]-Metrics-service"} > 0
        for: 2m
        labels:
          severity: critical
        annotations:
          summary: "Sai lệch đồng hồ trên Master {{ $labels.instance }}"
          description: |
            Node Master {{ $labels.instance }} có sai lệch thời gian (clock skew) lớn hơn 50ms trong hơn 2 phút.
            ▸ Giá trị hiện tại: {{ $value }} microseconds

      - alert: Yugabyte_YSQL_NewConnectionsSpike
        expr: rate(yb_ysqlserver_new_connection_total{job="[YugabyteDB-Service-Prod]-Metrics-service"}[5m]) > 50
        for: 2m
        labels:
          severity: warning
        annotations:
          summary: "Tốc độ tạo kết nối mới YSQL tăng cao"
          description: |
            Node {{ $labels.instance }} đang tạo > 50 kết nối mới mỗi giây. Có thể do không dùng connection pool hoặc truy cập bất thường.
            ▸ Tốc độ kết nối hiện tại: {{ $value }} kết nối/giây

      - alert: Yugabyte_YSQL_ConnectionsHigh
        expr: yb_ysqlserver_connection_total{job="[YugabyteDB-Service-Prod]-Metrics-service"} > 800
        for: 2m
        labels:
          severity: warning
        annotations:
          summary: "Số lượng kết nối YSQL cao trên {{ $labels.instance }}"
          description: |
            Node {{ $labels.instance }} duy trì > 800 kết nối tới YSQL. Có thể ứng dụng giữ kết nối quá lâu hoặc không dùng pool.
            ▸ Số kết nối hiện tại: {{ $value }}

      - alert: Yugabyte_YSQL_ConnectionRejected
        expr: rate(yb_ysqlserver_connection_over_limit_total{job="[YugabyteDB-Service-Prod]-Metrics-service"}[5m]) > 0
        for: 1m
        labels:
          severity: critical
        annotations:
          summary: "YSQL từ chối kết nối trên {{ $labels.instance }}"
          description: |
            Đã vượt max_connections trong 5 phút gần đây.
            ▸ Số lần từ chối mỗi giây: {{ $value }}

      - alert: Yugabyte_Schema_TablesSpike
        expr: increase(ycql_queries_system_schema_tables_count{job="[YugabyteDB-Service-Prod]-Metrics-service"}[5m]) > 5
        for: 1m
        labels:
          severity: warning
        annotations:
          summary: "Tăng đột biến bảng trong schema"
          description: "Tăng > 5 bảng trong 5 phút."

      - alert: Yugabyte_Schema_ViewsSpike
        expr: increase(ycql_queries_system_schema_views_count{job="[YugabyteDB-Service-Prod]-Metrics-service"}[5m]) > 3
        for: 1m
        labels:
          severity: warning
        annotations:
          summary: "Tăng đột biến view trong schema"
          description: "Tăng > 3 view trong 5 phút."

      - alert: Yugabyte_Schema_TriggersSpike
        expr: increase(ycql_queries_system_schema_triggers_count{job="[YugabyteDB-Service-Prod]-Metrics-service"}[5m]) > 3
        for: 1m
        labels:
          severity: warning
        annotations:
          summary: "Tăng đột biến trigger trong schema"
          description: "Tăng > 3 trigger trong 5 phút."

      - alert: Yugabyte_Schema_TypesSpike
        expr: increase(ycql_queries_system_schema_types_count{job="[YugabyteDB-Service-Prod]-Metrics-service"}[5m]) > 2
        for: 1m
        labels:
          severity: warning
        annotations:
          summary: "Tăng đột biến types trong schema"
          description: "Tăng > 2 types trong 5 phút."

      - alert: Yugabyte_SystemSizeEstimatesSpike
        expr: increase(ycql_queries_system_size_estimates_count{job="[YugabyteDB-Service-Prod]-Metrics-service"}[5m]) > 5
        for: 2m
        labels:
          severity: warning
        annotations:
          summary: "Kích thước hệ thống tăng bất thường"
          description: "Có thể do insert dữ liệu lớn hoặc test hiệu năng."

      - alert: Yugabyte_YSQL_ConnectionPoolHigh
        expr: ysql_conn_mgr_num_pools{job="[YugabyteDB-Service-Prod]-Metrics-service"} > 100
        for: 2m
        labels:
          severity: critical
        annotations:
          summary: "Số lượng connection pool cao"
          description: "Có thể do leak kết nối hoặc không đóng đúng cách."

      # MASTER EXPORTER ALERTS
      - alert: Yugabyte_Master_ExporterDown
        expr: pg_up{job="[YugabyteDB-Service-Prod]-Metrics-service", export_type="master_export"} == 0
        for: 1m
        labels:
          severity: critical
        annotations:
          summary: "Exporter master không phản hồi"
          description: "pg_up == 0 trên exporter master."

      - alert: Yugabyte_Master_ScrapeError
        expr: pg_exporter_last_scrape_error{job="[YugabyteDB-Service-Prod]-Metrics-service", export_type="master_export"} == 1
        for: 30s
        labels:
          severity: warning
        annotations:
          summary: "Lỗi scrape exporter master"
          description: "Prometheus gặp lỗi khi scrape dữ liệu từ master_export."

      - alert: Yugabyte_Master_ScrapeDurationHigh
        expr: pg_exporter_last_scrape_duration_seconds{job="[YugabyteDB-Service-Prod]-Metrics-service", export_type="master_export"} > 2
        for: 1m
        labels:
          severity: warning
        annotations:
          summary: "Scrape exporter master chậm"
          description: "Mất hơn 2 giây để scrape dữ liệu từ master_export."

      # TSERVER EXPORTER ALERTS
      - alert: Yugabyte_TServer_ExporterDown
        expr: pg_up{job="[YugabyteDB-Service-Prod]-Metrics-service", export_type="tserver_export"} == 0
        for: 1m
        labels:
          severity: critical
        annotations:
          summary: "Exporter tserver không phản hồi"
          description: "pg_up == 0 trên exporter tserver."

      - alert: Yugabyte_TServer_ScrapeError
        expr: pg_exporter_last_scrape_error{job="[YugabyteDB-Service-Prod]-Metrics-service", export_type="tserver_export"} == 1
        for: 30s
        labels:
          severity: warning
        annotations:
          summary: "Lỗi scrape exporter tserver"
          description: "Prometheus gặp lỗi khi scrape dữ liệu từ tserver_export."

      - alert: Yugabyte_TServer_ScrapeDurationHigh
        expr: pg_exporter_last_scrape_duration_seconds{job="[YugabyteDB-Service-Prod]-Metrics-service", export_type="tserver_export"} > 2
        for: 1m
        labels:
          severity: warning
        annotations:
          summary: "Scrape exporter tserver chậm"
          description: "Mất hơn 2 giây để scrape dữ liệu từ tserver_export."

      - alert: Yugabyte_TServer_CacheHitRateLow
        expr: rate(pg_response_cache_hits{job="[YugabyteDB-Service-Prod]-Metrics-service", export_type="tserver_export"}[5m])
              / rate(pg_response_cache_queries{job="[YugabyteDB-Service-Prod]-Metrics-service", export_type="tserver_export"}[5m]) < 0.3
        for: 3m
        labels:
          severity: warning
        annotations:
          summary: "Tỷ lệ hit cache thấp"
          description: "Tỷ lệ hit dưới 30% trong 5 phút."

      - alert: Yugabyte_TServer_CacheEntriesHigh
        expr: pg_response_cache_entries{job="[YugabyteDB-Service-Prod]-Metrics-service", export_type="tserver_export"} > 10000
        for: 5m
        labels:
          severity: info
        annotations:
          summary: "Số lượng entries cache cao"
          description: "Cache entries > 10,000. Kiểm tra cleanup."

      - alert: Yugabyte_TServer_CacheGCSpike
        expr: increase(pg_response_cache_gc_calls{job="[YugabyteDB-Service-Prod]-Metrics-service", export_type="tserver_export"}[5m]) > 50
        for: 1m
        labels:
          severity: warning
        annotations:
          summary: "GC cache tăng mạnh"
          description: "Số lần GC cache > 50 trong 5 phút."

      - alert: Yugabyte_TServer_CacheDisableSpike
        expr: increase(pg_response_cache_disable_calls{job="[YugabyteDB-Service-Prod]-Metrics-service", export_type="tserver_export"}[5m]) > 5
        for: 1m
        labels:
          severity: info
        annotations:
          summary: "Vô hiệu hóa cache tăng"
          description: "Có nhiều lần cache bị disable bất thường."

      - alert: Yugabyte_TServer_CacheQueriesSpike
        expr: increase(pg_response_cache_queries{job="[YugabyteDB-Service-Prod]-Metrics-service", export_type="tserver_export"}[5m]) > 1000
        for: 1m
        labels:
          severity: info
        annotations:
          summary: "Tăng đột biến truy vấn cache"
          description: "Số truy vấn cache tăng > 1000 trong 5 phút."
