groups:
- name: server-yugabyte
  rules:
  - alert: (Yugabyte)-Active
    expr: up{job='[YugabyteDB-Service-Prod]-Metrics service -- dịch vụ'} == 0
    for: 2m
    labels:
      severity: critical
    annotations:
      summary: "Node{{ $labels.instance }} không phản hồi"
      description: "Node {{ $labels.instance }} đã không phản hồi trong 2 phút. Kiểm tra kết nối hoặc trạng thái dịch vụ."

  - alert: (Yugabyte)-TimeError
    expr: hybrid_clock_error{job='[YugabyteDB-Service-Prod]-Metrics service -- dịch vụ'} > 500000
    for: 2m
    labels:
      severity: critical
    annotations:
      summary: "Sai số ước lượng giữa đồng hồ local và đồng hồ toàn cluster {{ $labels.instance }}"
      description: >
        Node Master {{ $labels.instance }} có sai số thời gian (clock error) lớn hơn 500ms trong hơn 2 phút.
        ▸ Giá trị hiện tại:
          - {{ $value }} microseconds
          - ~{{ printf "%.2f" (div $value 1000) }} milliseconds

  - alert: (Yugabyte)-LechGioHeThongMASTER
    expr: hybrid_clock_skew{job='[YugabyteDB-Service-Prod]-Metrics service -- dịch vụ'} > 0
    for: 2m
    labels:
      severity: critical
    annotations:
      summary: "Sai lệch đồng hồ trên node Master {{ $labels.instance }} vượt quá giới hạn"
      description: >
        Node Master {{ $labels.instance }} có sai lệch thời gian (clock skew) lớn hơn 50ms trong hơn 2 phút. Điều này có thể ảnh hưởng tới việc đồng bộ dữ liệu, tính nhất quán, hoặc gây lỗi giao dịch phân tán.
        ▸ Giá trị hiện tại: {{ $value }} microseconds

  - alert: (Yugabyte)-YSQLKetNoiMoiTangDotBien
    expr: rate(yb_ysqlserver_new_connection_total{job='[YugabyteDB-Service-Prod]-Metrics service -- dịch vụ'}[5m]) > 50
    for: 2m
    labels:
      severity: warning
    annotations:
      summary: "Tốc độ tạo kết nối mới tới YSQL trên {{ $labels.instance }} cao bất thường"
      description: >
        Node {{ $labels.instance }} đang tạo hơn 50 kết nối mới mỗi giây tới YSQL trong 5 phút qua. Điều này có thể do ứng dụng không sử dụng connection pool hoặc bị truy cập bất thường.
        ▸ Tốc độ kết nối hiện tại: {{ $value }} kết nối/giây

  - alert: (Yugabyte)-YSQLKetNoiHienTaiCao
    expr: yb_ysqlserver_connection_total{job='[YugabyteDB-Service-Prod]-Metrics service -- dịch vụ'} > 800
    for: 2m
    labels:
      severity: warning
    annotations:
      summary: "Số kết nối YSQL trên {{ $labels.instance }} đang ở mức cao"
      description: >
        Node {{ $labels.instance }} đang duy trì hơn 800 kết nối tới YSQL trong hơn 2 phút. Có thể do ứng dụng giữ kết nối quá lâu hoặc không dùng pool.
        ▸ Số kết nối hiện tại: {{ $value }}

  - alert: (Yugabyte)-YSQLBiTuChoiKetNoi
    expr: rate(yb_ysqlserver_connection_over_limit_total{job='[YugabyteDB-Service-Prod]-Metrics service -- dịch vụ'}[5m]) > 0
    for: 1m
    labels:
      severity: critical
    annotations:
      summary: "YSQL trên node {{ $labels.instance }} đang từ chối kết nối mới"
      description: >
        Node {{ $labels.instance }} đang từ chối các kết nối YSQL vì đã vượt quá giới hạn max_connections trong 5 phút gần đây.
        ▸ Số lần từ chối mỗi giây: {{ $value }}

  - alert: (Yugabyte)TangDotBienSoLuongBangTrongSchema
    expr: increase(ycql_queries_system_schema_tables_count{job='[YugabyteDB-Service-Prod]-Metrics service -- dịch vụ'}[5m]) > 5
    for: 1m
    labels:
      severity: warning
    annotations:
      summary: "Tăng đột biến số lượng bảng"
      description: "Số lượng bảng trong schema tăng hơn 5 bảng trong 5 phút."

  - alert: (Yugabyte)TangDotBienSoLuongViewTrongSchema
    expr: increase(ycql_queries_system_schema_views_count{job='[YugabyteDB-Service-Prod]-Metrics service -- dịch vụ'}[5m]) > 3
    for: 1m
    labels:
      severity: warning
    annotations:
      summary: "Tăng đột biến số lượng view"
      description: "Có nhiều view mới được tạo trong 5 phút."

  - alert: (Yugabyte)TangDotBienTriggersTrongSchema
    expr: increase(ycql_queries_system_schema_triggers_count{job='[YugabyteDB-Service-Prod]-Metrics service -- dịch vụ'}[5m]) > 3
    for: 1m
    labels:
      severity: warning
    annotations:
      summary: "Tăng đột biến số lượng triggers"
      description: "Có nhiều triggers mới được tạo. Cần kiểm tra schema."

  - alert: (Yugabyte)TangDotBienTypesTrongSchema
    expr: increase(ycql_queries_system_schema_types_count{job='[YugabyteDB-Service-Prod]-Metrics service -- dịch vụ'}[5m]) > 2
    for: 1m
    labels:
      severity: warning
    annotations:
      summary: "Tăng đột biến số lượng types"
      description: "Schema types tăng bất thường trong 5 phút."

  - alert: (Yugabyte)TangDotBienUocLuongKichThuoc
    expr: increase(ycql_queries_system_size_estimates_count{job='[YugabyteDB-Service-Prod]-Metrics service -- dịch vụ'}[5m]) > 5
    for: 2m
    labels:
      severity: warning
    annotations:
      summary: "Kích thước hệ thống tăng bất thường"
      description: "Có thể do insert nhiều dữ liệu hoặc load test."

  - alert: (Yugabyte)SoLuongYSQLConnectionPoolQuaCao
    expr: ysql_conn_mgr_num_pools{job='[YugabyteDB-Service-Prod]-Metrics service -- dịch vụ'} > 100
    for: 2m
    labels:
      severity: critical
    annotations:
      summary: "Số lượng connection pool cao"
      description: "Có thể do leak hoặc không đóng kết nối đúng cách."
