version: "3.8"

services:
  # Prometheus
  prometheus:
    image: prom/prometheus:v2.45.3
    container_name: emso-prometheus
    restart: always
    user: "root"
    mem_limit: 20g 
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./prometheus:/etc/prometheus/
      - ./data-prometheus-grafana/prometheus_data:/prometheus
    command:
      - "--config.file=/etc/prometheus/prometheus.yml"
      - "--storage.tsdb.path=/prometheus"
      - "--web.console.libraries=/usr/share/prometheus/console_libraries"
      - "--web.console.templates=/usr/share/prometheus/consoles"
      - "--web.enable-lifecycle"
      - "--web.config.file=/etc/prometheus/auth-web.yml"
      - "--storage.tsdb.retention.time=30d"
    ports:
      - 32800:9090
    links:
      - alertmanager:alertmanager
  # Alert Manager
  alertmanager:
    image: prom/alertmanager:v0.27.0
    container_name: emso-alertmanager
    restart: always
    ports:
      - 32801:9093
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./alertmanager/:/etc/alertmanager/
    command:
      - "--config.file=/etc/alertmanager/config.yml"
      - "--storage.path=/alertmanager"
      - "--web.config.file=/etc/alertmanager/config/auth-web.yml"

# Bot Alert Physical
  prometheus-bot-container:
    image: bachdangtuan/prom-golang-bot:latest
    container_name: emso-vipbot-container

    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./telegrambot-container/:/etc/telegrambot/
      - ./telegrambot-container/config.yaml:/config.yaml  
    ports:
      - 9088:9087
    restart: always