version: "3.8"

services:
  # Prometheus
  prometheus:
    image: prom/prometheus:v3.3.0
    container_name: emso-prometheus
    restart: always
    user: "root"
    mem_limit: 20g 
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./prometheus:/etc/prometheus/
      - ./data-prometheus-grafana/prometheus_data:/prometheus
    command:
      - "--config.file=/etc/prometheus/prometheus.yml"
      - "--storage.tsdb.path=/prometheus"
      - "--web.console.libraries=/usr/share/prometheus/console_libraries"
      - "--web.console.templates=/usr/share/prometheus/consoles"
      - "--web.enable-lifecycle"
      - "--web.config.file=/etc/prometheus/auth-web.yml"
      - "--storage.tsdb.retention.time=5d"
      - "--storage.tsdb.retention.size=50GB"
      # - "--storage.tsdb.min-block-duration=2h"
      # - "--storage.tsdb.max-block-duration=2h"
    ports:
      - 32800:9090
    links:
      - alertmanager:alertmanager
  # Alert Manager
  alertmanager:
    image: prom/alertmanager:v0.27.0
    container_name: emso-alertmanager
    restart: always
    mem_limit: 100m 
    ports:
      - 32801:9093
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./alertmanager/:/etc/alertmanager/
    command:
      - "--config.file=/etc/alertmanager/config.yml"
      - "--storage.path=/alertmanager"
      - "--web.config.file=/etc/alertmanager/config/auth-web.yml"
# Bot Alert Physical
  prometheus-bot-container:
    image: bachdangtuan/prom-golang-bot:latest
    container_name: emso-vipbot
    mem_limit: 100m 
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./telegrambot/:/etc/telegrambot/
      - ./telegrambot/config.yaml:/config.yaml  
    ports:
      - 32802:9087
    restart: always

  grafana:
    image: grafana/grafana:latest
    container_name: emso-grafana
    user: "root"
    restart: always
    environment:
      GF_INSTALL_PLUGINS: "grafana-clock-panel,grafana-simple-json-datasource"
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./data-prometheus-grafana/grafana_data:/var/lib/grafana
      - ./grafana/provisioning/:/etc/grafana/provisioning/
    env_file:
      - ./grafana/config.monitoring
    ports:
      - 3000:3000
    depends_on:
      - prometheus


# Bot Alert Kubernetes
  prometheus-bot-kubernetes:
    image: bachdangtuan/prom-golang-bot:latest
    container_name: emso-vipbot-kubernetes
    mem_limit: 100m 
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./telegrambot-kubernetes/:/etc/telegrambot/
      - ./telegrambot-kubernetes/config.yaml:/config.yaml  
    ports:
      - 32803:9087
    restart: always
