groups:
- name: Container
  rules:
  - alert: Container Status
    expr: container_state_status{status='exited',name='golang-app'} == 1
    for: 10s
    labels:
      severity: khẩn cấp
      category: container-memory
      container_name: golang-app
      app_type: Server Demo
    annotations:
      summary: Container killed (instance {{ $labels.instance }}  )
      description: |
       Container name:{{ $labels.name }}
       A container has disappeared

  - alert: Container Memory
    expr: container_memory_usage_bytes{name="golang-app",instance="10.0.0.55:11092"} 
    for: 10s
    labels:
      severity: khẩn cấp
      app_type: Server Demo
      category: container-memory    
      container_name: golang-app
    annotations:
      summary: "RAM container quá 90%"
      description: |
      
        Container name: {{ $labels.name }}

        Thông tin cụ thể: 

          RAM USED: {{ query (printf "container_memory_usage_bytes{name='golang-app',instance=~'%s'}"   $labels.instance) | first | value | humanize}} 

