groups:
- name: Container
  rules:
  - alert: Container Tắt
    expr: container_state_status{status='exited',name='searching-service'} == 1
    for: 10s
    labels:
      severity: khẩn cấp
      category: container
      container_name: searching-service
      app_type: Server Demo
    annotations:
      summary: Container killed (instance {{ $labels.instance }}  ) {{ $labels.name }}
      description: |
       Container name:{{ $labels.name }}
       A container has disappeared

  - alert: Container Memory
    expr: container_memory_usage_bytes{name="searching-service",instance="10.0.0.55:11092"} 
    for: 10s
    labels:
      severity: khẩn cấp
      category: container-memory
      app_type: Server Demo
      container_name: searching-service
    annotations:
      summary: " RAM container > 90%"     
      description: |
      
        CONTAINER NAME: {{ $labels.name }}

        Thông tin cụ thể: 

              * RAM USED: {{ query (printf "container_memory_usage_bytes{name='searching-service',instance=~'%s'}"   $labels.instance) | first | value | humanize}} 