groups:
  - name: redis-alerts
    rules:
      - alert: (Redis)-BlockedClients
        expr: redis_blocked_clients{job='[Redis-Server-Prod]-Metrics service -- dịch vụ'} > 0
        for: 1m
        labels:
          severity: warning
        annotations:
          summary: "Redis đang có client bị block"
          description: "Phát hiện ít nhất một client đang bị block. Cần kiểm tra pipeline hoặc slow command."

      - alert: (Redis)-AOFRewriteTooLong
        expr: redis_aof_last_rewrite_duration_sec{job='[Redis-Server-Prod]-Metrics service -- dịch vụ'} > 300
        for: 2m
        labels:
          severity: warning
        annotations:
          summary: "Redis AOF rewrite mất quá nhiều thời gian"
          description: "Quá trình AOF rewrite gần nhất mất hơn 5 phút. Có thể do file AOF quá lớn."

      - alert: (Redis)-AOFWriteFailed
        expr: redis_aof_last_write_status{job='[Redis-Server-Prod]-Metrics service -- dịch vụ'} == 0
        for: 30s
        labels:
          severity: critical
        annotations:
          summary: "Redis ghi AOF thất bại"
          description: "AOF không ghi thành công trong lần ghi gần nhất. Cần kiểm tra đĩa hoặc hệ thống."

      - alert: (Redis)-MemoryFragmentationHigh
        expr: redis_allocator_frag_ratio{job='[Redis-Server-Prod]-Metrics service -- dịch vụ'} > 1.5
        for: 3m
        labels:
          severity: warning
        annotations:
          summary: "Redis memory fragmentation cao"
          description: "Tỷ lệ fragmentation của bộ nhớ Redis vượt 1.5. Cần xem xét cấu hình hoặc defrag."

      - alert: (Redis)-DefragmentationRunningTooLong
        expr: redis_active_defrag_running{job='[Redis-Server-Prod]-Metrics service -- dịch vụ'} == 1
        for: 10m
        labels:
          severity: info
        annotations:
          summary: "Redis đang chạy defragmentation liên tục"
          description: "Quá trình defrag đang chạy hơn 10 phút. Có thể đang dọn bộ nhớ hoặc có lỗi tối ưu hóa."

      - alert: (Redis)-BlockedClients
        expr: redis_blocked_clients{job='[Redis-Server-Prod]-Metrics service -- dịch vụ'} > 0
        for: 1m
        labels:
          severity: warning
        annotations:
          summary: "Redis đang có client bị block"
          description: "Một hoặc nhiều client đang bị block. Kiểm tra tình trạng pipeline hoặc slow command."

      - alert: (Redis)-AOFWriteFailed
        expr: redis_aof_last_write_status{job='[Redis-Server-Prod]-Metrics service -- dịch vụ'} == 0
        for: 30s
        labels:
          severity: critical
        annotations:
          summary: "Redis ghi AOF thất bại"
          description: "Trạng thái ghi AOF gần nhất không thành công. Cần kiểm tra lỗi ổ đĩa hoặc cấu hình."

      - alert: (Redis)-AOFRewriteTooLong
        expr: redis_aof_last_rewrite_duration_sec{job='[Redis-Server-Prod]-Metrics service -- dịch vụ'} > 300
        for: 2m
        labels:
          severity: warning
        annotations:
          summary: "Thời gian rewrite AOF quá dài"
          description: "Quá trình rewrite AOF mất hơn 5 phút, có thể do AOF quá lớn hoặc thiếu tài nguyên hệ thống."

      - alert: (Redis)-DefragmentationRunningTooLong
        expr: redis_active_defrag_running{job='[Redis-Server-Prod]-Metrics service -- dịch vụ'} == 1
        for: 10m
        labels:
          severity: info
        annotations:
          summary: "Redis đang defragment lâu"
          description: "Redis đang chạy chống phân mảnh bộ nhớ liên tục hơn 10 phút."

      - alert: (Redis)-MemoryFragmentationHigh
        expr: redis_mem_fragmentation_ratio{job='[Redis-Server-Prod]-Metrics service -- dịch vụ'} > 1.5
        for: 5m
        labels:
          severity: warning
        annotations:
          summary: "Tỷ lệ phân mảnh bộ nhớ cao"
          description: "Tỷ lệ fragmentation > 1.5, bộ nhớ sử dụng không hiệu quả."

      - alert: (Redis)-MemoryUsageNearLimit
        expr: redis_memory_used_bytes{job='[Redis-Server-Prod]-Metrics service -- dịch vụ'} / redis_memory_max_bytes{job='[Redis-Server-Prod]-Metrics service -- dịch vụ'} > 0.9
        for: 2m
        labels:
          severity: critical
        annotations:
          summary: "Redis sắp đầy bộ nhớ"
          description: "Bộ nhớ Redis đã dùng hơn 90% giới hạn `maxmemory`. Cần mở rộng hoặc dọn bộ nhớ."

      - alert: (Redis)-ForkTooSlow
        expr: redis_latest_fork_seconds{job='[Redis-Server-Prod]-Metrics service -- dịch vụ'} > 2
        for: 1m
        labels:
          severity: warning
        annotations:
          summary: "Fork Redis mất thời gian dài"
          description: "Fork Redis mất hơn 2 giây. Có thể ảnh hưởng đến hiệu năng khi lưu RDB hoặc AOF."

      - alert: (Redis)-LoadingDumpFile
        expr: redis_loading_dump_file{job='[Redis-Server-Prod]-Metrics service -- dịch vụ'} == 1
        for: 2m
        labels:
          severity: info
        annotations:
          summary: "Redis đang load RDB"
          description: "Redis đang trong quá trình khởi động và load file dump.rdb."

      - alert: (Redis)-LazyFreeBacklogHigh
        expr: redis_lazyfree_pending_objects{job='[Redis-Server-Prod]-Metrics service -- dịch vụ'} > 1000
        for: 2m
        labels:
          severity: warning
        annotations:
          summary: "Nhiều object đang chờ lazyfree"
          description: "Hệ thống có hơn 1000 đối tượng đang chờ giải phóng (lazyfree)."

      - alert: (Redis)-ReplicaLag
        expr: redis_master_repl_offset{job='[Redis-Server-Prod]-Metrics service -- dịch vụ'} < 1000
        for: 2m
        labels:
          severity: warning
        annotations:
          summary: "Replica có độ trễ"
          description: "Replication offset thấp, có thể replica không theo kịp master."

      - alert: (Redis)-RSSMemoryTooHigh
        expr: redis_memory_used_rss_bytes{job='[Redis-Server-Prod]-Metrics service -- dịch vụ'} > redis_memory_used_bytes{job='[Redis-Server-Prod]-Metrics service -- dịch vụ'} * 1.5
        for: 3m
        labels:
          severity: warning
        annotations:
          summary: "Bộ nhớ RSS thực tế cao hơn nhiều so với memory logic"
          description: "Có thể do phân mảnh hoặc leak bộ nhớ nội bộ Redis."

      - alert: (Redis)-ScriptMemoryHigh
        expr: redis_memory_used_scripts_bytes{job='[Redis-Server-Prod]-Metrics service -- dịch vụ'} > 50 * 1024 * 1024
        for: 2m
        labels:
          severity: info
        annotations:
          summary: "Script Redis đang dùng nhiều bộ nhớ"
          description: "Script Redis dùng hơn 50MB RAM. Có thể cần xem lại số lượng script lưu trữ."
