groups:
  - name: redis-exporter-monitoring
    rules:
      # 1. Exporter không hoạt động
      - alert: (RedisExporter)-Down
        expr: redis_up{job='[Redis-Server-Prod]-Metrics service -- dịch vụ'} == 0
        for: 1m
        labels:
          severity: critical
        annotations:
          summary: "Redis Exporter không phản hồi"
          description: "Exporter không trả dữ liệu cho Prometheus. Kiểm tra container hoặc service exporter."

      # 2. Lỗi scrape gần nhất
      - alert: (RedisExporter)-LastScrapeError
        expr: redis_exporter_last_scrape_error{job='[Redis-Server-Prod]-Metrics service -- dịch vụ'} == 1
        for: 30s
        labels:
          severity: warning
        annotations:
          summary: "Lỗi khi scrape Redis exporter"
          description: "Prometheus không thể scrape dữ liệu từ Redis exporter lần gần nhất."

      # 3. Thời gian kết nối scrape quá cao
      - alert: (RedisExporter)-ScrapeConnectTimeHigh
        expr: redis_exporter_last_scrape_connect_time_seconds{job='[Redis-Server-Prod]-Metrics service -- dịch vụ'} > 1
        for: 1m
        labels:
          severity: warning
        annotations:
          summary: "Thời gian kết nối tới Redis exporter cao"
          description: "Mất hơn 1 giây để kết nối tới Redis exporter. Có thể do mạng hoặc Redis phản hồi chậm."

      # 4. Thời gian scrape tổng quá cao
      - alert: (RedisExporter)-ScrapeDurationHigh
        expr: redis_exporter_last_scrape_duration_seconds{job='[Redis-Server-Prod]-Metrics service -- dịch vụ'} > 2
        for: 1m
        labels:
          severity: warning
        annotations:
          summary: "Thời gian scrape Redis exporter cao"
          description: "Thời gian scrape từ Prometheus vượt 2 giây. Có thể Redis phản hồi chậm hoặc exporter gặp vấn đề."

      # 5. Tổng số lần lỗi scrape tăng
      - alert: (RedisExporter)-TargetScrapeErrors
        expr: increase(redis_target_scrape_request_errors_total{job='[Redis-Server-Prod]-Metrics service -- dịch vụ'}[5m]) > 5
        for: 1m
        labels:
          severity: warning
        annotations:
          summary: "Tăng số lần lỗi scrape Redis exporter"
          description: "Prometheus gặp nhiều lỗi khi scrape Redis exporter trong 5 phút gần đây."

      # 6. Số client đang được Redis giám sát
      # - alert: (RedisExporter)-MonitoringClientHigh
      #   expr: redis_monitoring_clients{job='[Redis-Server-Prod]-Metrics service -- dịch vụ'} > 10
      #   for: 2m
      #   labels:
      #     severity: info
      #   annotations:
      #     summary: "Số lượng client được Redis giám sát cao"
      #     description: "Hiện có hơn 10 client đang trong trạng thái MONITOR. Điều này có thể ảnh hưởng hiệu năng Redis."

      # 7. Scrape không được cập nhật (đếm không tăng)
      - alert: (RedisExporter)-ScrapeStuck
        expr: rate(redis_exporter_scrapes_total{job='[Redis-Server-Prod]-Metrics service -- dịch vụ'}[5m]) == 0
        for: 2m
        labels:
          severity: critical
        annotations:
          summary: "Redis Exporter không được scrape"
          description: "Không có scrape nào thành công từ Redis Exporter trong 5 phút qua."
