groups:
- name: Container
  rules:
  - alert: Container Tắt
    expr: container_state_status{status='exited'} == 1
    for: 10s
    labels:
      severity: critical
      category: container-status
      container_name: searching-service
    annotations:
      summary: Container killed (instance {{ $labels.instance }}  ) {{ $labels.name }}
      description: |
       Container name:{{ $labels.name }}
       A container has disappeared

