groups:
- name: Container
  rules:
  - alert: Container Status
    expr: container_state_status{status='exited',name='jira-cluster-isofh_node1_1'} == 1
    for: 10s
    labels:
      severity: khẩn cấp
      category: container-status
      container_name: jira-cluster-isofh_node1_1
      app_type: Server Nội Bộ Isofh
    annotations:
      summary: Container killed (instance {{ $labels.instance }}  )
      description: |
       Container name:{{ $labels.name }}
       Container bị tắt

  - record: demo_check_ram_container
    expr: container_memory_usage_bytes{name="jira-cluster-isofh_node1_1",instance="10.0.0.20:19093"} > 999999999

  - alert: Container Memory
    expr: container_memory_usage_bytes{name="jira-cluster-isofh_node1_1",instance="10.0.0.20:19093"} > 21330644995
    for: 10s
    labels:
      severity: khẩn cấp
      app_type: Server Nội Bộ Isofh
      category: container-memory    
      container_name: jira-cluster-isofh_node1_1
    annotations:
      summary: "RAM container quá 90%"
      description: |
      
        Container name: {{ $labels.name }}

        Thông tin cụ thể: 

          RAM USED: {{ query (printf "container_memory_usage_bytes{name='jira-cluster-isofh_node1_1',instance=~'%s'}"   $labels.instance) | first | value | humanize}} 

