# bot Tuấn
telegram_token: "6300638795:AAFjtwl3qM9BIUXoa-dNqV1ElLDpyTvjGHg"
template_path: "/etc/telegrambot/template.tmpl"
time_zone: "Asia/Ho_Chi_Minh"
split_token: "|"
time_outdata: "02/01/2006 15:04:05"
split_msg_byte: 10000